name: Database build, query, and autograding

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: hw_1:SQL
      run: |
        cd hw_1
        sudo apt-get install sqlite3 libsqlite3-dev
        wget https://15445.courses.cs.cmu.edu/fall2019/files/imdb-cmudb2019.db.gz
        gunzip imdb-cmudb2019.db.gz
        sqlite3 imdb-cmudb2019.db
        CREATE INDEX ix_people_name ON people (name);
        CREATE INDEX ix_titles_type ON titles (type);
        CREATE INDEX ix_titles_primary_title ON titles (primary_title);
        CREATE INDEX ix_titles_original_title ON titles (original_title);
        CREATE INDEX ix_akas_title_id ON akas (title_id);
        CREATE INDEX ix_akas_title ON akas (title);
        CREATE INDEX ix_crew_title_id ON crew (title_id);
        CREATE INDEX ix_crew_person_id ON crew (person_id);
        .read placeholder/q1_sample.sql
        .read placeholder/q2_uncommon_type.sql
        .read placeholder/q3_tv_vs_movie.sql
        .read placeholder/q4_old_is_not_gold.sql
        .read placeholder/q5_percentage.sql
        .read placeholder/q6_dubbed_smash.sql
        .read placeholder/q7_imdb_250.sql
        .read placeholder/q8_number_of_actors.sql
        .read placeholder/q9_movie_names.sql
        .read placeholder/q10_genre_counts.sql
